import type { SystemSheetSchema } from './types';

// Mirrors the mechanical content of the official TSR AD&D 1E character record
// sheet (THAC0, the 5-category saves, weapon attacks, per-ability adjustments,
// thief skills, class abilities, movement/attacks/XP), plus the field set from
// the "AD&D 1st Edition Player Character Sheet (Unearthed Arcana Version)" by
// Steve Jensen (identity/adjustment/breakdown fields below) — not either
// sheet's printed layout or artwork. Grounded in data/osric-stub.md,
// specifically its "Where 1E and 2E Diverge" section, which is why this schema
// differs from add2e.ts exactly where it does:
//   - No `nonWeaponProficiencies` field — that's a 2E-only proficiency-slot
//     system per the stub; 1E core rules have no equivalent.
const schema: SystemSheetSchema = {
  gameSystem: 'ADD1E',
  fields: [
    { key: 'thac0', label: 'THAC0', column: 'combat', kind: 'number', keyStat: true },
    { key: 'ac', label: 'AC', column: 'combat', kind: 'number', keyStat: true, icon: 'shield' },
    { key: 'numberOfAttacks', label: '# of Attacks', column: 'combat', kind: 'string' },
    { key: 'experiencePoints', label: 'Experience Points', column: 'stats', kind: 'number' },
    { key: 'xpNeededForNextLevel', label: 'Experience Needed for Next Level', column: 'stats', kind: 'number' },
    { key: 'alignment', label: 'Alignment', column: 'stats', kind: 'string' },
    { key: 'playersName', label: "Player's Name", column: 'stats', kind: 'string' },
    { key: 'sex', label: 'Sex', column: 'stats', kind: 'string' },
    { key: 'height', label: 'Height', column: 'stats', kind: 'string' },
    { key: 'weight', label: 'Weight', column: 'stats', kind: 'string' },
    { key: 'age', label: 'Age', column: 'stats', kind: 'string' },
    { key: 'homeland', label: 'Homeland', column: 'stats', kind: 'string' },
    { key: 'clan', label: 'Clan', column: 'stats', kind: 'string' },
    { key: 'liege', label: 'Liege', column: 'stats', kind: 'string' },
    { key: 'deity', label: 'Deity', column: 'stats', kind: 'string' },
    {
      key: 'savingThrows',
      label: 'Saving Throws',
      column: 'saves',
      kind: 'record-fixed',
      keys: ['paralyzation', 'rod', 'petrification', 'breath', 'spell'],
      labels: {
        paralyzation: 'Paralysis / Poison / Death',
        rod: 'Rod / Staff / Wand',
        petrification: 'Petrification / Polymorph',
        breath: 'Breath Weapon',
        spell: 'Spells',
      },
    },
    {
      // Per-ability derived combat/utility sub-modifiers the official sheet prints
      // next to each ability score.
      key: 'strAdjustments',
      label: 'Strength Adjustments',
      column: 'stats',
      kind: 'record-fixed',
      keys: ['toHit', 'damage', 'weightAllowance', 'opensDoors', 'bendBarsLiftGates'],
      labels: {
        toHit: 'To Hit',
        damage: 'Damage',
        weightAllowance: 'Weight Allowance',
        opensDoors: 'Opens Doors',
        bendBarsLiftGates: 'Bend Bars / Lift Gates',
      },
    },
    {
      key: 'intAdjustments',
      label: 'Intelligence Adjustments',
      column: 'stats',
      kind: 'record-fixed',
      keys: ['bonusLanguages', 'spellLearnChance', 'minSpellsPerLevel', 'maxSpellsPerLevel'],
      labels: {
        bonusLanguages: 'Bonus Languages',
        spellLearnChance: 'Chance to Learn Spell (%)',
        minSpellsPerLevel: 'Minimum Spells per Level',
        maxSpellsPerLevel: 'Maximum Spells per Level',
      },
    },
    {
      key: 'wisAdjustments',
      label: 'Wisdom Adjustments',
      column: 'stats',
      kind: 'record-fixed',
      keys: ['magicAttackAdjustment', 'bonusSpells', 'spellFailureChance'],
      labels: {
        magicAttackAdjustment: 'Magic Attack Adjustment',
        bonusSpells: 'Bonus Spells',
        spellFailureChance: 'Spell Failure Chance (%)',
      },
    },
    {
      key: 'dexAdjustments',
      label: 'Dexterity Adjustments',
      column: 'stats',
      kind: 'record-fixed',
      keys: ['missileAttackAdjustment', 'armorClassAdjustment', 'reactionAdjustment'],
      labels: {
        missileAttackAdjustment: 'Missile Attack Adjustment',
        armorClassAdjustment: 'Armor Class Adjustment',
        reactionAdjustment: 'Reaction Adjustment',
      },
    },
    {
      key: 'conAdjustments',
      label: 'Constitution Adjustments',
      column: 'stats',
      kind: 'record-fixed',
      keys: ['hpAdjustment', 'systemShockSurvival', 'resurrectionSurvival'],
      labels: {
        hpAdjustment: 'Hit Point Adjustment',
        systemShockSurvival: 'System Shock Survival (%)',
        resurrectionSurvival: 'Resurrection Survival (%)',
      },
    },
    {
      key: 'chrAdjustments',
      label: 'Charisma Adjustments',
      column: 'stats',
      kind: 'record-fixed',
      keys: ['maxHenchmen', 'loyaltyBase', 'reactionAdjustment'],
      labels: {
        maxHenchmen: 'Maximum Henchmen',
        loyaltyBase: 'Loyalty Base (%)',
        reactionAdjustment: 'Reaction Adjustment (%)',
      },
    },
    {
      key: 'acBreakdown',
      label: 'Armor Class Breakdown',
      column: 'combat',
      kind: 'record-fixed',
      keys: ['base', 'withoutShield', 'rear', 'withoutDexterityBonus'],
      labels: {
        base: 'Base',
        withoutShield: 'Without Shield',
        rear: 'Rear',
        withoutDexterityBonus: 'Without Dexterity Bonus',
      },
    },
    {
      key: 'movementRates',
      label: 'Movement Rates',
      column: 'combat',
      kind: 'record-fixed',
      keys: ['base', 'encumbered', 'fly', 'swim', 'climb'],
      labels: {
        base: 'Base Move Rate',
        encumbered: 'Encumbered Move Rate',
        fly: 'Fly Speed',
        swim: 'Swim Speed',
        climb: 'Climb Speed',
      },
    },
    { key: 'encumbrance', label: 'Total Encumbrance (Coins)', column: 'combat', kind: 'number' },
    { key: 'encounterSpeed', label: 'Encounter Speed', column: 'combat', kind: 'number' },
    {
      key: 'weaponAttacks',
      label: 'Weapons',
      column: 'combat',
      kind: 'table',
      columns: [
        { key: 'weapon', label: 'Weapon', type: 'text' },
        { key: 'proficiency', label: 'Proficiency', type: 'text' },
        { key: 'attackRate', label: 'Attack Rate / ROF', type: 'text' },
        { key: 'thac0', label: 'THAC0', type: 'number' },
        { key: 'damage', label: 'Damage', type: 'text' },
        { key: 'range', label: 'Range', type: 'text' },
        { key: 'special', label: 'Special Abilities', type: 'text' },
      ],
    },
    {
      key: 'animalCompanions',
      label: 'Animal Companions',
      column: 'combat',
      kind: 'table',
      columns: [
        { key: 'name', label: 'Name', type: 'text' },
        { key: 'hp', label: 'HP', type: 'number' },
        { key: 'thac0', label: 'THAC0', type: 'number' },
        { key: 'attacks', label: '# Attacks', type: 'text' },
        { key: 'damage', label: 'Damage', type: 'text' },
        { key: 'ac', label: 'AC', type: 'number' },
        { key: 'abilities', label: 'Abilities', type: 'text' },
      ],
    },
    {
      key: 'turnUndeadTable',
      label: 'Turn Undead',
      column: 'skills',
      kind: 'record-fixed',
      keys: [
        'skeleton',
        'zombie',
        'ghoul',
        'shadow',
        'wight',
        'ghast',
        'wraith',
        'mummy',
        'spectre',
        'vampire',
        'ghost',
        'lich',
        'special',
      ],
      labels: {
        skeleton: 'Skeleton',
        zombie: 'Zombie',
        ghoul: 'Ghoul',
        shadow: 'Shadow',
        wight: 'Wight',
        ghast: 'Ghast',
        wraith: 'Wraith',
        mummy: 'Mummy',
        spectre: 'Spectre',
        vampire: 'Vampire',
        ghost: 'Ghost',
        lich: 'Lich',
        special: 'Special',
      },
    },
    {
      // Class abilities: Paladin's lay on hands, Ranger's tracking, Bard's legend
      // lore, etc.
      key: 'classAbilities',
      label: 'Class & Racial Abilities',
      column: 'stats',
      kind: 'string-list',
    },
    {
      key: 'thiefSkills',
      label: 'Thief Skills (%)',
      column: 'skills',
      kind: 'record-fixed',
      keys: [
        'pickPockets',
        'openLocks',
        'findRemoveTraps',
        'moveSilently',
        'hideInShadows',
        'hearNoise',
        'climbWalls',
        'readLanguages',
      ],
      labels: {
        pickPockets: 'Pick Pockets',
        openLocks: 'Open Locks',
        findRemoveTraps: 'Find / Remove Traps',
        moveSilently: 'Move Silently',
        hideInShadows: 'Hide in Shadows',
        hearNoise: 'Hear Noise',
        climbWalls: 'Climb Walls',
        readLanguages: 'Read Languages',
      },
    },
    {
      key: 'treasure',
      label: 'Treasure',
      column: 'stats',
      kind: 'record-fixed',
      keys: ['platinum', 'gold', 'silver'],
      labels: {
        platinum: 'Platinum',
        gold: 'Gold',
        silver: 'Silver',
      },
    },
    {
      key: 'languages',
      label: 'Languages',
      column: 'stats',
      kind: 'string-list',
    },
    {
      key: 'spellSlots',
      label: 'Spell Slots',
      column: 'combat',
      kind: 'spell-slots',
      levels: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
    },
  ],
};

export default schema;
