import type { SystemSheetSchema } from './types';

// Mirrors the mechanical content of a standard D&D 4E character sheet layout
// (defenses, healing surges/second wind, the fixed 17-skill list with a
// trained flag, powers by usage tier, action points, paragon path/epic
// destiny) — not any specific publisher's printed layout or artwork. Skills
// use a fixed keyset (4E's list, unlike 3.5E/PF2E, has no player-defined
// sub-types). Powers/attacks/rituals use the `table` field kind rather than
// modeling each stat block's full ½-level/ability/class/feat/enhancement/misc
// breakdown — totals only, same "store the fillable value, not the
// derivation" approach used throughout this project's other systems.
const schema: SystemSheetSchema = {
  gameSystem: '4E',
  fields: [
    { key: 'ac', label: 'AC', column: 'combat', kind: 'number', keyStat: true, icon: 'shield' },
    {
      key: 'otherDefenses',
      label: 'Other Defenses',
      column: 'combat',
      kind: 'record-fixed',
      keys: ['fortitude', 'reflex', 'will'],
      labels: { fortitude: 'Fortitude', reflex: 'Reflex', will: 'Will' },
    },
    { key: 'initiative', label: 'Initiative', column: 'combat', kind: 'number', keyStat: true },
    { key: 'speed', label: 'Speed', column: 'combat', kind: 'string' },
    { key: 'passiveInsight', label: 'Passive Insight', column: 'combat', kind: 'number' },
    { key: 'passivePerception', label: 'Passive Perception', column: 'combat', kind: 'number' },
    { key: 'actionPoints', label: 'Action Points', column: 'combat', kind: 'number' },
    { key: 'tempHp', label: 'Temporary HP', column: 'combat', kind: 'number' },
    { key: 'bloodied', label: 'Bloodied', column: 'combat', kind: 'number' },
    { key: 'surgeValue', label: 'Surge Value', column: 'combat', kind: 'number' },
    { key: 'surgesPerDay', label: 'Surges per Day', column: 'combat', kind: 'number' },
    { key: 'currentSurges', label: 'Current Surges', column: 'combat', kind: 'number' },
    { key: 'secondWindUsed', label: 'Second Wind Used', column: 'combat', kind: 'string' },
    {
      key: 'skills',
      label: 'Skills',
      column: 'skills',
      kind: 'record-fixed',
      keys: [
        'acrobatics',
        'arcana',
        'athletics',
        'bluff',
        'diplomacy',
        'dungeoneering',
        'endurance',
        'heal',
        'history',
        'insight',
        'intimidate',
        'nature',
        'perception',
        'religion',
        'stealth',
        'streetwise',
        'thievery',
      ],
      labels: {
        acrobatics: 'Acrobatics',
        arcana: 'Arcana',
        athletics: 'Athletics',
        bluff: 'Bluff',
        diplomacy: 'Diplomacy',
        dungeoneering: 'Dungeoneering',
        endurance: 'Endurance',
        heal: 'Heal',
        history: 'History',
        insight: 'Insight',
        intimidate: 'Intimidate',
        nature: 'Nature',
        perception: 'Perception',
        religion: 'Religion',
        stealth: 'Stealth',
        streetwise: 'Streetwise',
        thievery: 'Thievery',
      },
    },
    { key: 'trainedSkills', label: 'Trained Skills', column: 'skills', kind: 'string-list' },
    {
      key: 'attacks',
      label: 'Attacks',
      column: 'combat',
      kind: 'table',
      columns: [
        { key: 'name', label: 'Attack', type: 'text' },
        { key: 'vsDefense', label: 'vs. Defense', type: 'text' },
        { key: 'attackBonus', label: 'Attack Bonus', type: 'text' },
        { key: 'damage', label: 'Damage', type: 'text' },
        { key: 'range', label: 'Range', type: 'text' },
        { key: 'notes', label: 'Notes', type: 'text' },
      ],
    },
    {
      key: 'powers',
      label: 'Powers',
      column: 'combat',
      kind: 'table',
      columns: [
        { key: 'name', label: 'Power', type: 'text' },
        { key: 'usage', label: 'At-Will / Encounter / Daily / Utility', type: 'text' },
        { key: 'levelKeywords', label: 'Level & Keywords', type: 'text' },
        { key: 'typeRange', label: 'Type & Range', type: 'text' },
        { key: 'effects', label: 'Effects', type: 'text' },
        { key: 'special', label: 'Special', type: 'text' },
      ],
    },
    { key: 'featsSpecialFeatures', label: 'Feats & Special Features', column: 'stats', kind: 'string-list' },
    { key: 'rituals', label: 'Rituals', column: 'stats', kind: 'string-list' },
    { key: 'magicItems', label: 'Magic Items', column: 'stats', kind: 'string-list' },
    { key: 'companionsAllies', label: 'Companions & Allies', column: 'stats', kind: 'string-list' },
    { key: 'languages', label: 'Languages', column: 'stats', kind: 'string-list' },
    {
      key: 'carryingCapacity',
      label: 'Carrying Capacity',
      column: 'combat',
      kind: 'record-fixed',
      keys: ['normalLoad', 'heavyLoad', 'maxDragLoad'],
      labels: { normalLoad: 'Normal Load', heavyLoad: 'Heavy Load', maxDragLoad: 'Max Drag Load' },
    },
    { key: 'wealth', label: 'Money & Other Wealth', column: 'stats', kind: 'text' },
    { key: 'experiencePoints', label: 'Experience Points', column: 'stats', kind: 'number' },
    { key: 'xpNeededForNextLevel', label: 'Experience Needed for Next Level', column: 'stats', kind: 'number' },
    { key: 'alignment', label: 'Alignment', column: 'stats', kind: 'string' },
    { key: 'deityReligion', label: 'Deity / Religion', column: 'stats', kind: 'string' },
    { key: 'paragonPath', label: 'Paragon Path', column: 'stats', kind: 'string' },
    { key: 'epicDestiny', label: 'Epic Destiny', column: 'stats', kind: 'string' },
    { key: 'age', label: 'Age', column: 'stats', kind: 'string' },
    { key: 'sex', label: 'Sex', column: 'stats', kind: 'string' },
    { key: 'size', label: 'Size', column: 'stats', kind: 'string' },
    { key: 'height', label: 'Height', column: 'stats', kind: 'string' },
    { key: 'weight', label: 'Weight', column: 'stats', kind: 'string' },
    { key: 'eyes', label: 'Eyes', column: 'stats', kind: 'string' },
    { key: 'hair', label: 'Hair', column: 'stats', kind: 'string' },
    { key: 'skin', label: 'Skin', column: 'stats', kind: 'string' },
    { key: 'description', label: 'Description', column: 'stats', kind: 'text' },
    { key: 'personality', label: 'Personality', column: 'stats', kind: 'text' },
    { key: 'contactsFriends', label: 'Contacts & Friends', column: 'stats', kind: 'text' },
    { key: 'enemies', label: 'Enemies', column: 'stats', kind: 'text' },
    { key: 'quotes', label: 'Quotes', column: 'stats', kind: 'text' },
    { key: 'goals', label: 'Will (Goals & Motivations)', column: 'stats', kind: 'text' },
    { key: 'backgroundNotes', label: 'Background & Notes', column: 'stats', kind: 'text' },
  ],
};

export default schema;
