import type { SystemSheetSchema } from './types';

// Mirrors the mechanical content of the official Free League "The One Ring"
// 2nd Edition character sheet — not its printed layout or artwork. Confirmed
// identical field structure across all four culture-specific sheet variants
// (Dwarves, Elves, Hobbits, Men — only the decorative corner emblem differs
// per culture), so one schema covers every TOR2E character regardless of
// Heroic Culture. Note: TOR2E's third attribute is Strength (not "Body" —
// that's the 1st Edition name; see lib/game-systems/registry.ts's TOR2E entry,
// updated to match).
const schema: SystemSheetSchema = {
  gameSystem: 'TOR2E',
  fields: [
    { key: 'age', label: 'Age', column: 'stats', kind: 'string' },
    { key: 'heroicCulture', label: 'Heroic Culture', column: 'stats', kind: 'string' },
    { key: 'culturalBlessing', label: 'Cultural Blessing', column: 'stats', kind: 'string' },
    { key: 'standardOfLiving', label: 'Standard of Living', column: 'stats', kind: 'string' },
    { key: 'calling', label: 'Calling', column: 'stats', kind: 'string' },
    { key: 'shadowPath', label: 'Shadow Path', column: 'stats', kind: 'string' },
    { key: 'patron', label: 'Patron', column: 'stats', kind: 'string' },
    { key: 'distinctiveFeatures', label: 'Distinctive Features', column: 'stats', kind: 'string' },
    { key: 'flaws', label: 'Flaws', column: 'stats', kind: 'string' },
    { key: 'history', label: 'History', column: 'stats', kind: 'text' },
    {
      key: 'rewards',
      label: 'Rewards',
      column: 'stats',
      kind: 'record-fixed',
      keys: ['adventurePoints', 'skillPoints', 'fellowshipPoints'],
      labels: { adventurePoints: 'Adventure Points', skillPoints: 'Skill Points', fellowshipPoints: 'Fellowship Points' },
    },
    { key: 'valour', label: 'Valour (Heart TN)', column: 'stats', kind: 'number' },
    { key: 'wisdom', label: 'Wisdom (Wits TN)', column: 'stats', kind: 'number' },
    {
      key: 'targetNumbers',
      label: 'Target Numbers',
      column: 'stats',
      kind: 'record-fixed',
      keys: ['strength', 'heart', 'wits'],
      labels: { strength: 'Strength', heart: 'Heart', wits: 'Wits' },
    },
    {
      key: 'endurance',
      label: 'Endurance',
      column: 'combat',
      kind: 'record-fixed',
      keys: ['max', 'current', 'load', 'fatigue'],
      labels: { max: 'Max', current: 'Current', load: 'Load', fatigue: 'Fatigue' },
    },
    {
      key: 'hope',
      label: 'Hope',
      column: 'combat',
      kind: 'record-fixed',
      keys: ['max', 'current', 'shadow', 'scars'],
      labels: { max: 'Max', current: 'Current', shadow: 'Shadow', scars: 'Scars' },
    },
    { key: 'conditions', label: 'Conditions', column: 'combat', kind: 'string-list' },
    { key: 'injury', label: 'Injury', column: 'combat', kind: 'text' },
    {
      key: 'combatProficiencies',
      label: 'Combat Proficiencies',
      column: 'combat',
      kind: 'record-fixed',
      keys: ['axes', 'bows', 'spears', 'swords'],
      labels: { axes: 'Axes', bows: 'Bows', spears: 'Spears', swords: 'Swords' },
    },
    {
      key: 'skills',
      label: 'Skills',
      column: 'skills',
      kind: 'record-fixed',
      keys: [
        'awe',
        'athletics',
        'awareness',
        'hunting',
        'song',
        'craft',
        'enhearten',
        'travel',
        'insight',
        'healing',
        'courtesy',
        'battle',
        'persuade',
        'stealth',
        'scan',
        'explore',
        'riddle',
        'lore',
      ],
      labels: {
        awe: 'Awe',
        athletics: 'Athletics',
        awareness: 'Awareness',
        hunting: 'Hunting',
        song: 'Song',
        craft: 'Craft',
        enhearten: 'Enhearten',
        travel: 'Travel',
        insight: 'Insight',
        healing: 'Healing',
        courtesy: 'Courtesy',
        battle: 'Battle',
        persuade: 'Persuade',
        stealth: 'Stealth',
        scan: 'Scan',
        explore: 'Explore',
        riddle: 'Riddle',
        lore: 'Lore',
      },
    },
    {
      key: 'warGear',
      label: 'War Gear',
      column: 'combat',
      kind: 'table',
      columns: [
        { key: 'weapon', label: 'Weapon', type: 'text' },
        { key: 'damage', label: 'Damage', type: 'text' },
        { key: 'injury', label: 'Injury', type: 'text' },
        { key: 'load', label: 'Load', type: 'text' },
        { key: 'notes', label: 'Notes', type: 'text' },
      ],
    },
    {
      key: 'armourAndHelm',
      label: 'Armour & Helm',
      column: 'combat',
      kind: 'table',
      columns: [
        { key: 'item', label: 'Item', type: 'text' },
        { key: 'protection', label: 'Protection', type: 'number' },
        { key: 'load', label: 'Load', type: 'number' },
      ],
    },
    {
      key: 'shield',
      label: 'Shield',
      column: 'combat',
      kind: 'record-fixed',
      keys: ['protection', 'parryBase', 'parryTotal', 'load'],
      labels: { protection: 'Protection', parryBase: 'Parry (Base)', parryTotal: 'Parry (Total)', load: 'Load' },
    },
    { key: 'treasure', label: 'Treasure', column: 'stats', kind: 'number' },
  ],
};

export default schema;
